# Generated by Django 6.0.4 on 2026-04-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings_app', '0003_buildingnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='last_news_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
