# Generated by Django 6.0.4 on 2026-04-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings_app", "0006_advocacylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="city_council_district",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="state_assembly_district",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="state_senate_district",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
