# Generated by Django 6.0.4 on 2026-04-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings_app", "0008_councildistrict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="councildistrict",
            name="last_synced",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
