# Generated by Django 6.0.4 on 2026-04-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings_app", "0009_councildistrict_last_synced_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="cached_executive_summary",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="building",
            name="summary_last_generated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
