# Generated by Django 6.0.4 on 2026-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings_app", "0010_building_cached_executive_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="councildistrict",
            name="committees",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="NYC Council committee memberships, e.g. ['Housing & Buildings (Chair)']",  # noqa: E501
            ),
        ),
    ]
